export const ALL_TODOS_CONTENT_ID = "ALL_TODOS_CONTENT_ID";

export const ACTIVE_TODOS_CONTENT_ID = "ACTIVE_TODOS_CONTENT_ID";

export const COMPLETED_TODOS_CONTENT_ID = "COMPLETED_TODOS_CONTENT_ID";
